Prefix: ' &7&l[境界] '
#等级经验
level-formula: '(2.0*level^2)/2.0+120.0*(level/5.0)+35.0'
stage-upgrade:
  1: 4
  2: 8
  3: 12
  4: 16
  5: 20
  6: 26
  7: 32
  8: 38
  9: 44
  10: 50
realm-upgrade:
  1: 2
  2: 4
  3: 6
  4: 8
  5: 10
  6: 14
  7: 18
  8: 22
  9: 26
  10: 30
  11: 32
  12: 34
  13: 36
  14: 38
  15: 40
  16: 45
  17: 50
  18: 55
  19: 60
  20: 66
  21: 88
stone:
  stage:
    id: STONE
    data: 0
    name: '&a[ &3阶段突破石 &a]'
    lore:
      - '&7用于增加段位突破点'
      - ''
      - ' &3使用一个 &7- 右键'
      - ' &3全部使用 &7- Shift+右键'
  realm:
    id: STONE
    data: 0
    name: '&a[ &a境界突破石 &a]'
    lore:
      - '&7用于增加境界突破点'
      - ''
      - ' &3使用一个 &7- 右键'
      - ' &3全部使用 &7- Shift+右键'