name: JustLevel
main: net.sakuragame.eternal.justlevel.JustLevel
version: ${project.version}
author: 'justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - DataManager
  - PlaceholderAPI
  - MythicMobs
  - DragonCore

commands:
  jlevel:
    description: show all command
    aliases:
      - level