name: JustLevel
main: net.sakuragame.megumi.justlevel.JustLevel
version: ${project.version}
author: 'Justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - ClientManager
  - PlaceholderAPI

commands:
  jlevel:
    description: show all command
    aliases:
      - level