name: JustLevel
main: net.sakuragame.megumi.justlevel.Main
version: ${project.version}
author: 'Justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - ClientManager

commands:
  jlevel:
    description: show all command